### PR TITLE
Set the `format` of `marshmallow.fields.Float` fields to `float`

### PR DESCRIPTION
**Pull request by ddorian**
See `float` format for number data types https://swagger.io/docs/specification/data-models/data-types/

### CODE REVIEW

**Comment by lafrech** [comment]
Shouldn't it be `double`?

https://swagger.io/docs/specification/data-models/data-types/

Or system-dependent?

https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex

> Floating point numbers are usually implemented using double in C; information about the precision and internal representation of floating point numbers for the machine on which your program is running is available in [sys.float_info](https://docs.python.org/3/library/sys.html#sys.float_info).

We can't rely (solely) on `sys.float.info` as the doc may be generated on another machine than the one running the API.

**Comment by ddorian** [comment]
> Shouldn't it be double?

Yes.

> We can't rely (solely) on sys.float.info as the doc may be generated on another machine than the one running the API.

That is the problem with the dev IMO. What do you propose?

**Comment by lafrech** [comment]
Since we can't tell, I'd say leave things as is and let the user override if needed.

We may want to document this, though.

**Comment by ddorian** [comment]
Maybe we can add a validator to make the "type" (example on Function/Method fields) or format (Float,Number,etc) required ?

**Comment by lafrech** [comment]
I'm sorry, I don't understand what you mean.

**Comment by ddorian** [comment]
> I'm sorry, I don't understand what you mean.

I've added a validator that checks that all Float fields should have "type" defined, just to be "consistent" on the openapi output.
I've done that for "FunctionField" & "MethodField", but made "type" required there.

**Pull request closed without merging**
