### PR TITLE
Fix schema name that has end with space for redoc ui and elements ui

### PR DESCRIPTION
**Pull request by duchuyvp**
I strip `component_id` before register a new schema when to prevent its name has some bad space, generated spec has schama name that end with space like 'Schema name ' doesn't work with `redoc` ui (by ReDoc) and `elements` ui (by Stoplight)

### CODE REVIEW

**Comment by lafrech** [comment]
AFAIU, the space in the schema name a user error that may be a bit tricky to spot but that should be easily fixed.

I may be convinced otherwise but I don't think apispec should engage in this. We can't workaround all typos.

**Comment by duchuyvp** [comment]
You have point out that maybe it's a user error, I did try named a schema like "Pet In Schema" and the error occur, cause after remove postfix "Schema" in that name, it's stay "Pet In " and this does not look like user error or typo. Even I can simply fix this by replace the name with "Pet In" or "Pet InSchema" but the second way may looks like typo error.

**Comment by lafrech** [comment]
Good point. We could improve the schema name generator to strip spaces there.

How do you create the schema?

Schemas are generally created as classes so you can't have spaces in their names.

```py
class PetSchema(Schema):
    ...
```

**Comment by duchuyvp** [comment]
Sorry about delay. 

I used `from_dict` to generate schema.

```python
from marshmallow.fields import String

pet_schema = Schema.from_dict({"name": String()}, name="Pet In Schema")
```

**Comment by lafrech** [comment]
OK. 

Users probably shouldn't give names with spaces in the first place but since it is not forbidden, I have no objection to stripping the generated name in the default name resolver: https://github.com/marshmallow-code/apispec/blob/cb90ed2931a5450a652fb32c34f082730d2f2dd1/src/apispec/ext/marshmallow/__init__.py#L87-L93.

**Comment by duchuyvp** [comment]
Thanks for your consider. Would the branch be merge?

**Comment by duchuyvp** [comment]
pre-commit.ci run

**Comment by sloria** [comment]
Made some minor fixups so it's ready to merge. Thanks for the PR!

**Pull request merged**
