### PR TITLE
Manage only/exclude marshmallow attributes on autoreferencing schema

### PR DESCRIPTION
**Pull request by inkhey**
Auto-referencing schema feature doesn't support specific parameters from marshmallow schema instance like `only` and `exclude`.

That's why this pull request is about auto-generate new schema class when `only` and `exclude` appear using `exclude` parameters in `opts` of schema. Apispec save also a dict of auto-generated schema class with and id system to avoid uniqueness trouble.

This patch break compatibility with old auto-referencing schema feature because `auto_referencing` boolean is now needed to activate auto-referencing and schema class returned by default to `auto_schema_name_resolver `may be not the same as before.

I do think that's not a big deal because auto-ref is probably not used widely now, but this need to be discussed.

### CODE REVIEW

**Comment by odarbelaeze** [comment]
I feel this is needed, tho I just implemented this for our use case like:

```diff
+def get_schema_signature(schema):
+    """Return a signature for a given schema (instance or class)
+    :param schema: instance or class of marshmallow.Schema
+    :return: schema signature
+    """
+    schema_class = get_schema_class(schema)
+    schema_instance = get_schema_instance(schema)
+    interest_fields = {
+        'dump_only': None,
+        'exclude': None,
+        'extra': None,
+        'load_only': None,
+        # 'many': None,
+        'only': tuple(),
+        # 'ordered': None,
+        'partial': None,
+        # 'prefix': None,
+        'strict': None,
+    }
+    values = {field: getattr(schema, field) for field in interest_fields}
+    signature = '|'.join(
+        field + ':' + str(values[field] if values[field] is not None else default)
+        for field, default in interest_fields.items()
+    )
+    return schema_class, signature
```

That's used as the `key` of the `refs` dictionary. With a very small diff, this allows to discern references of this kind:

```python
SPEC.definition('Company', schema=schema.CompanySchema())
SPEC.definition('CompanyCreate', schema=schema.CompanySchema.for_create())
SPEC.definition('CompanyUpdate', schema=schema.CompanySchema.for_update())
SPEC.definition('CompanyUpdatePartial', schema=schema.CompanySchema.for_update(partial=True))
SPEC.definition('PaginatedCompanies', schema=schema.PaginatedCompanySchema())
```

Let me know if people would be interested on me making this PR.

**Comment by lebouquetin** [comment]
hey @sloria what about merging this MR ? 

For history, we (@buxx @inkhey and I) did propose merged MR in the past. See : 

- https://github.com/marshmallow-code/apispec/pull/167
- https://github.com/marshmallow-code/apispec/pull/162

We are working on hapic, based on apispec and we need some improvments that we prefer to have upstream.

Auto-referencing feature with include/exclude support in Marshmallow schemas would be very helpfull.

Thank's for your answer

**Comment by lafrech** [comment]
@lebouquetin I'm not sure you realize you're pushing to the branch submitted here.

**Comment by lebouquetin** [comment]
@lafrech I'm not sure I understand correctly.

What we do with @inkhey and @buxx : 

- send MRs to https://github.com/marshmallow-code/apispec/ in order to have our modifications upstream
- work on a friendly fork of apispec for not being blocked during MR validation process.

As soon as our MR is merged (this may be after some refactoring - no problem), our fork `hapic_apispec` will disappear (or will continue as a development base for our stuff).

Hm... but I understand what you're speaking about... the package name... you're totally right this is a wrong commit for current MR.

**Comment by lafrech** [comment]
> What we do with @inkhey and @buxx : 
> 
> - send MRs to https://github.com/marshmallow-code/apispec/ in order to have our modifications upstream
> - work on a friendly fork of apispec for not being blocked during MR validation process.
> 
> As soon as our MR is merged (this may be after some refactoring - no problem), our fork `hapic_apispec` will disappear (or will continue as a development base for our stuff).

Yes, perfectly fine. Great, in fact. This is the way to go.

> Hm... but I understand what you're speaking about... the package name... you're totally right this is a wrong commit for current MR.

Exactly. I just figured you were pushing to your fork without realizing that those changes were added to this PR automatically (including the renaming, etc.).

I didn't mean to sound harsh or anything. Just raising your attention.

**Comment by lebouquetin** [comment]
> Exactly. I just figured you were pushing to your fork without realizing that those changes were added to this PR automatically (including the renaming, etc.).
> 
> I didn't mean to sound harsh or anything. Just raising your attention.
Merge state

No worries... you were right to warn me (I didn't realize). We'll fix. Thanks !

**Comment by sloria** [comment]
Closing this as this has gone stale. Feel free to re-open this if it's still of interest to you and after the history is cleaned up.

**Comment by lafrech** [comment]
@lebouquetin, @inkhey, I wanted to write a friendly note about this and waited to be done with the refactor.

The bad news is that there were so many changes in the code this PR is nearly impossible to rebase. You're much better off applying your changes from scratch on the latest revision in `dev`.

The good news is that hopefully the refactor made things much easier for you.

To be honest, I don't like that autoreferencing feature  so much. I totally understand the need, as I don't like to repeat myself either, but I don't think it is too much of a hassle to call `definition` on every schema I want to register, and it allows me to choose the ones I want and specify the name I want in a clear and explicit fashion. This feature adds a bit of complexity for a small gain IMHO. Besides, it is a bit broken because it only tests for `List` as a container, while other fields could be containers too (`Dict` in marshmallow 3, let alone custom fields) so one might want to add a mechanism to register new container fields.

I believe that thanks to the refactor, it should be easier to implement this in a custom plugin of yours that would inherit from `MarshmallowPlugin`. This way, you wouldn't have to maintain a fork. If you succeed with this, we may even get `inspect_schema_for_auto_referencing` out of here into your custom plugin. This is just my feeling right now, I could be convinced otherwise and I don't have a strong feeling about it. Besides, it looks much less ugly now that the schema name resolver function is passed to the plugin directly, rather than passed to the spec so it is not that bad after all.

I hope you manage to get rid of your fork, be it thanks to a custom plugin or by having your code merged into apispec.

**Comment by lafrech** [comment]
@lebouquetin, @inkhey, any comment about this before we release v1.0?

Thanks.

**Comment by inkhey** [comment]
@lafrech Thank for alerting us about apispec new plugin mecanism. We actually don't have much time to work on pluginification of this feature but as we clearly need apispec with this feature we will have to do it .

Nice to see that apispec reach 1.0 version soon.

**Pull request closed without merging**
