### PR TITLE
Add Tornado extension

### PR DESCRIPTION
**Pull request by lucasrcosta**

### CODE REVIEW

**Comment by lucascosta** [comment]
The failing parts of the build are not from this PR.

**Comment by lucasrcosta** [comment]
The error is due to the update release of marshmallow (https://github.com/marshmallow-code/marshmallow/releases/tag/2.7.0).

**Comment by lucasrcosta** [comment]
Fixed https://github.com/marshmallow-code/apispec/pull/64

**Comment by sloria** [comment]
This is amazing. Thanks a lot!

**Pull request merged**
