### PR TITLE
Drop deprecated distutils.version.LooseVersion in favor of packaging.…

### PR DESCRIPTION
**Pull request by theonlynexus**
distutils.version.LooseVersion has been deprecated, instead use packaging.version.Version

### CODE REVIEW

**Comment by lafrech** [comment]
Thanks.

See discussion here: https://github.com/marshmallow-code/marshmallow/pull/1903 and in #739.

Since we expose `OpenAPIVersion`, this is a breaking change -> [6.0](https://github.com/marshmallow-code/apispec/milestone/5).

No rush since this is just a deprecation warning and it won't break until Python 12.

**Comment by theonlynexus** [comment]
Oh... I see. Sorry for the double trouble. Shall I just close the PR since you're already on the job?

**Comment by lafrech** [comment]
No pb. You may leave the PR open, even fix it. Just don't expect it to be merged soon.

**Comment by theonlynexus** [comment]
1- sorry again for submitting a buggy PR. 
2- sorry for taking such a long time to fix it... I had a BIG injection of life.
3- Everything should be OK, now. Please check it out?

**Comment by lafrech** [comment]
Hi.

No pb with the delay. As I said, this is no emergency.

I didn't take the time to review thoroughly but I saw a mention of backward compatibility. Since we'll be shipping this in a major update, we don't have to worry about backward compatibility.

Thanks for your work on this.

**Comment by judgeaxl** [comment]
Related to this, is there any way to hide only specific deprecation warnings in Python? I get hundreds of these in my current app tests, from apispec and other libraries, and while the warning itself can be considered unimportant at the moment, it still clutters my test reports, and I still want to see other, possibly relevant warnings, so a blanket filter on DeprecationWarning doesn't really work for me.

**Comment by theonlynexus** [comment]
> [...] I get hundreds of these in my current app tests, from apispec and other libraries, and while the warning itself can be considered unimportant at the moment, it still clutters my test reports[...]

This is exactly why I made the PR.

**Review by LucasHartridge — APPROVED** [review]

**Review by LucasHartridge — COMMENTED** [review]
I have tested this code and fixed the problem. On our code base, the Unit tests are passing and I didn't see any problem. Shall we merge it?

**Comment by lafrech** [comment]
See comment above. Since this is technically a breaking change, this is v6.

I intend to ship v6 soon. See v6 milestone.

I just need to finish and polish (documentation, etc.) #778. The rest is more or less trivial.

Nothing blocking, just time.

Meanwhile, this is just a deprecation warning about a breakage in Python 12.

**Comment by lafrech** [comment]
Achieved in #801. I removed `OpenAPIVersion` and dropped compatibility.

**Comment by lafrech** [comment]
Change released in 6.0.0b1.

**Pull request closed without merging**
