### PR TITLE
Allow helpers to return None

### PR DESCRIPTION
**Pull request by lafrech**
Fixes https://github.com/marshmallow-code/apispec/issues/331.

### CODE REVIEW

**Comment by lafrech** [comment]
@sloria, @Bangertm, any comment before I merge this?

**Review by Bangertm — COMMENTED** [review]
Looks good.  Tested with the api that was causing the problem and it works great.

**Comment by lafrech** [comment]
Alright, let's merge this. It's never too late to rework the CHANGELOG if it is unclear.

**Comment by sloria** [comment]
Thanks guys. Since this is a bugfix, looks like it's time to release! 🚢 🇮🇹 

I'll get #338 merged in then cut a release.

**Pull request merged**
