### PR TITLE
Add example of using a security_scheme to the documentation

### PR DESCRIPTION
**Pull request by teancom**
This is in reference to issue #586 - I have added an example of using a security scheme to protect a route, in a way that would have helped me personally. Hopefully it helps others as well!

### CODE REVIEW

**Comment by sloria** [comment]
Thanks! Looks good to me. Can you also copy this to `README.rst`? Also, please add yourself to `AUTHORS.rst`.

**Comment by teancom** [comment]
Done! Thanks again for apispec, btw. It was lovely (and possibly helped get me a job! We'll see next week. 😄)

**Comment by lafrech** [comment]
Thanks for taking the time to document this.

The example in the README lacks the declaration of the security scheme for the resource both in the code and in the json output. It is only present in the yaml output.

Also I'm not sure about documenting this in the quickstart (readme or index). This should be in a dedicated second step section. There are several auth schemes and there is no reason to document api key here and not the others.

**Comment by teancom** [comment]
Oops! Sorry, yeah, updated the missing bits. I have no (real) opinion as to whether this should all be broken out into a separate doc or whatnot. I do think having an example of authorization/security in the first place people look would be a nice thing to have, and I'm using api key because that's what I happened to be using. But if you want to swap it to be JWT or oath2 or whatever, I'm fine with that!

**Comment by sloria** [comment]
This is OK for now. Putting this in a dedicated section would be a good idea, but it's good to have it somewhere for the time being.

**Pull request merged**
